### ISSUE TITLE
rsyslog on admin node creates /var/log/nodes/.log

### ISSUE THREAD

**Issue by aspiers** [crowbar/crowbar#1368]
The `logging` barclamp configures `/etc/rsyslog.d/10-crowbar-server.conf` on the admin node to contain:

    # split remote logs by hostname
    $template DynaFile,"/var/log/nodes/%HOSTNAME%.log"
    *.* -?DynaFile

However at some point this results in `/var/log/nodes/.log` being created.  On one of my admin nodes it contains:

    Aug 13 12:00:22  logrotate: last message repeated 3 times
    Aug 13 15:32:56  crowbar_app[2891]: last message repeated 3 times
    Aug 13 15:32:56  crowbar_app[2891]: last message repeated 16 times
    Aug 13 15:32:56  crowbar_app[2891]: last message repeated 22 times

and on the other:

    Aug 10 11:45:27  logrotate: last message repeated 3 times
    Aug 11 13:00:30  logrotate: last message repeated 3 times
    Aug 13 10:46:36  logrotate: last message repeated 3 times
    Aug 14 10:45:42  logrotate: last message repeated 3 times

so it's probably related to logrotate.

**Comment by aspiers** [comment]
@vuntz I think we probably fixed this by now?

**Comment by vuntz** [comment]
I think so too.
