### ISSUE TITLE
FR: Should be able to navigate to an active barclamp proposal from a node's page in web UI

### ISSUE THREAD

**Issue by aspiers** [crowbar/crowbar#911]
The node view page currently shows a list of all barclamp proposals active on that node.  Clicking any one of them highlights all nodes that proposal currently applies to in the list of nodes at the bottom of the page, using a blue background.  This is a nice feature, but IMHO it would be more useful if clicking on that barclamp navigated directly to the proposal, so that you could view attributes and then optionally click the `Edit Proposal` button to edit them.  The node highlighting could still happen on mouseover, so that nice functionality would not have to be discarded.

**Comment by aspiers** [comment]
@bkutil @tboerger Another very old but still relevant FR.

**Comment by bkutil** [comment]
> This is a nice feature, but IMHO it would be more useful if clicking on that barclamp navigated directly to the proposal

IIUC, this is what is currently happening. A node show page contains list of proposals applied to the node, each of them links to proposal edit view.

**Comment by aspiers** [comment]
Of course you're right.
